// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: payment/paymentpb/payment.proto

/*
Package paymentpb is a generated protocol buffer package.

It is generated from these files:
	payment/paymentpb/payment.proto

It has these top-level messages:
	Charge
	Refund
	Card
	ChargeRequest
	GetRequest
	RefundRequest
	ListRequest
	ChargeList
*/
package paymentpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Currency int32

const (
	Currency_CUR_RESERVED Currency = 0
	Currency_AFN          Currency = 1
	Currency_ALL          Currency = 2
	Currency_AMD          Currency = 3
	Currency_ANG          Currency = 4
	Currency_ARS          Currency = 5
	Currency_AUD          Currency = 6
	Currency_AWG          Currency = 7
	Currency_AZN          Currency = 8
	Currency_BAM          Currency = 9
	Currency_BBD          Currency = 10
	Currency_BGN          Currency = 11
	Currency_BHD          Currency = 12
	Currency_BMD          Currency = 13
	Currency_BND          Currency = 14
	Currency_BOB          Currency = 15
	Currency_BRL          Currency = 16
	Currency_BSD          Currency = 17
	Currency_BWP          Currency = 18
	Currency_BYN          Currency = 19
	Currency_BYR          Currency = 20
	Currency_BZD          Currency = 21
	Currency_CAD          Currency = 22
	Currency_CLP          Currency = 23
	Currency_CNY          Currency = 24
	Currency_COP          Currency = 25
	Currency_CRC          Currency = 26
	Currency_CUP          Currency = 27
	Currency_CZK          Currency = 28
	Currency_DKK          Currency = 29
	Currency_DOP          Currency = 30
	Currency_DZD          Currency = 31
	Currency_EEK          Currency = 32
	Currency_EGP          Currency = 33
	Currency_EUR          Currency = 34
	Currency_FJD          Currency = 35
	Currency_FKP          Currency = 36
	Currency_GBP          Currency = 37
	Currency_GGP          Currency = 38
	Currency_GHC          Currency = 39
	Currency_GIP          Currency = 40
	Currency_GTQ          Currency = 41
	Currency_GYD          Currency = 42
	Currency_HKD          Currency = 43
	Currency_HNL          Currency = 44
	Currency_HRK          Currency = 45
	Currency_HUF          Currency = 46
	Currency_IDR          Currency = 47
	Currency_ILS          Currency = 48
	Currency_IMP          Currency = 49
	Currency_INR          Currency = 50
	Currency_IQD          Currency = 51
	Currency_IRR          Currency = 52
	Currency_ISK          Currency = 53
	Currency_JEP          Currency = 54
	Currency_JMD          Currency = 55
	Currency_JOD          Currency = 56
	Currency_JPY          Currency = 57
	Currency_KES          Currency = 58
	Currency_KGS          Currency = 59
	Currency_KHR          Currency = 60
	Currency_KPW          Currency = 61
	Currency_KRW          Currency = 62
	Currency_KWD          Currency = 63
	Currency_KYD          Currency = 64
	Currency_KZT          Currency = 65
	Currency_LAK          Currency = 66
	Currency_LBP          Currency = 67
	Currency_LKR          Currency = 68
	Currency_LRD          Currency = 69
	Currency_LTL          Currency = 70
	Currency_LVL          Currency = 71
	Currency_LYD          Currency = 72
	Currency_MAD          Currency = 73
	Currency_MKD          Currency = 74
	Currency_MNT          Currency = 75
	Currency_MUR          Currency = 76
	Currency_MXN          Currency = 77
	Currency_MWK          Currency = 78
	Currency_MYR          Currency = 79
	Currency_MZN          Currency = 80
	Currency_NAD          Currency = 81
	Currency_NGN          Currency = 82
	Currency_NIO          Currency = 83
	Currency_NOK          Currency = 84
	Currency_NPR          Currency = 85
	Currency_NZD          Currency = 86
	Currency_OMR          Currency = 87
	Currency_PAB          Currency = 88
	Currency_PEN          Currency = 89
	Currency_PHP          Currency = 90
	Currency_PKR          Currency = 91
	Currency_PLN          Currency = 92
	Currency_PYG          Currency = 93
	Currency_QAR          Currency = 94
	Currency_RON          Currency = 95
	Currency_RSD          Currency = 96
	Currency_RUB          Currency = 97
	Currency_RUR          Currency = 98
	Currency_SAR          Currency = 99
	Currency_SBD          Currency = 100
	Currency_SCR          Currency = 101
	Currency_SEK          Currency = 102
	Currency_SGD          Currency = 103
	Currency_SHP          Currency = 104
	Currency_SOS          Currency = 105
	Currency_SRD          Currency = 106
	Currency_SVC          Currency = 107
	Currency_SYP          Currency = 108
	Currency_THB          Currency = 109
	Currency_TND          Currency = 110
	Currency_TRL          Currency = 111
	Currency_TRY          Currency = 112
	Currency_TTD          Currency = 113
	Currency_TWD          Currency = 114
	Currency_TZS          Currency = 115
	Currency_UAH          Currency = 116
	Currency_UGX          Currency = 117
	Currency_AED          Currency = 118
	Currency_UYU          Currency = 119
	Currency_UZS          Currency = 120
	Currency_VEF          Currency = 121
	Currency_VND          Currency = 122
	Currency_XCD          Currency = 123
	Currency_YER          Currency = 124
	Currency_ZAR          Currency = 125
	Currency_ZMW          Currency = 126
	Currency_ZWD          Currency = 127
	Currency_USD          Currency = 128
)

var Currency_name = map[int32]string{
	0:   "CUR_RESERVED",
	1:   "AFN",
	2:   "ALL",
	3:   "AMD",
	4:   "ANG",
	5:   "ARS",
	6:   "AUD",
	7:   "AWG",
	8:   "AZN",
	9:   "BAM",
	10:  "BBD",
	11:  "BGN",
	12:  "BHD",
	13:  "BMD",
	14:  "BND",
	15:  "BOB",
	16:  "BRL",
	17:  "BSD",
	18:  "BWP",
	19:  "BYN",
	20:  "BYR",
	21:  "BZD",
	22:  "CAD",
	23:  "CLP",
	24:  "CNY",
	25:  "COP",
	26:  "CRC",
	27:  "CUP",
	28:  "CZK",
	29:  "DKK",
	30:  "DOP",
	31:  "DZD",
	32:  "EEK",
	33:  "EGP",
	34:  "EUR",
	35:  "FJD",
	36:  "FKP",
	37:  "GBP",
	38:  "GGP",
	39:  "GHC",
	40:  "GIP",
	41:  "GTQ",
	42:  "GYD",
	43:  "HKD",
	44:  "HNL",
	45:  "HRK",
	46:  "HUF",
	47:  "IDR",
	48:  "ILS",
	49:  "IMP",
	50:  "INR",
	51:  "IQD",
	52:  "IRR",
	53:  "ISK",
	54:  "JEP",
	55:  "JMD",
	56:  "JOD",
	57:  "JPY",
	58:  "KES",
	59:  "KGS",
	60:  "KHR",
	61:  "KPW",
	62:  "KRW",
	63:  "KWD",
	64:  "KYD",
	65:  "KZT",
	66:  "LAK",
	67:  "LBP",
	68:  "LKR",
	69:  "LRD",
	70:  "LTL",
	71:  "LVL",
	72:  "LYD",
	73:  "MAD",
	74:  "MKD",
	75:  "MNT",
	76:  "MUR",
	77:  "MXN",
	78:  "MWK",
	79:  "MYR",
	80:  "MZN",
	81:  "NAD",
	82:  "NGN",
	83:  "NIO",
	84:  "NOK",
	85:  "NPR",
	86:  "NZD",
	87:  "OMR",
	88:  "PAB",
	89:  "PEN",
	90:  "PHP",
	91:  "PKR",
	92:  "PLN",
	93:  "PYG",
	94:  "QAR",
	95:  "RON",
	96:  "RSD",
	97:  "RUB",
	98:  "RUR",
	99:  "SAR",
	100: "SBD",
	101: "SCR",
	102: "SEK",
	103: "SGD",
	104: "SHP",
	105: "SOS",
	106: "SRD",
	107: "SVC",
	108: "SYP",
	109: "THB",
	110: "TND",
	111: "TRL",
	112: "TRY",
	113: "TTD",
	114: "TWD",
	115: "TZS",
	116: "UAH",
	117: "UGX",
	118: "AED",
	119: "UYU",
	120: "UZS",
	121: "VEF",
	122: "VND",
	123: "XCD",
	124: "YER",
	125: "ZAR",
	126: "ZMW",
	127: "ZWD",
	128: "USD",
}
var Currency_value = map[string]int32{
	"CUR_RESERVED": 0,
	"AFN":          1,
	"ALL":          2,
	"AMD":          3,
	"ANG":          4,
	"ARS":          5,
	"AUD":          6,
	"AWG":          7,
	"AZN":          8,
	"BAM":          9,
	"BBD":          10,
	"BGN":          11,
	"BHD":          12,
	"BMD":          13,
	"BND":          14,
	"BOB":          15,
	"BRL":          16,
	"BSD":          17,
	"BWP":          18,
	"BYN":          19,
	"BYR":          20,
	"BZD":          21,
	"CAD":          22,
	"CLP":          23,
	"CNY":          24,
	"COP":          25,
	"CRC":          26,
	"CUP":          27,
	"CZK":          28,
	"DKK":          29,
	"DOP":          30,
	"DZD":          31,
	"EEK":          32,
	"EGP":          33,
	"EUR":          34,
	"FJD":          35,
	"FKP":          36,
	"GBP":          37,
	"GGP":          38,
	"GHC":          39,
	"GIP":          40,
	"GTQ":          41,
	"GYD":          42,
	"HKD":          43,
	"HNL":          44,
	"HRK":          45,
	"HUF":          46,
	"IDR":          47,
	"ILS":          48,
	"IMP":          49,
	"INR":          50,
	"IQD":          51,
	"IRR":          52,
	"ISK":          53,
	"JEP":          54,
	"JMD":          55,
	"JOD":          56,
	"JPY":          57,
	"KES":          58,
	"KGS":          59,
	"KHR":          60,
	"KPW":          61,
	"KRW":          62,
	"KWD":          63,
	"KYD":          64,
	"KZT":          65,
	"LAK":          66,
	"LBP":          67,
	"LKR":          68,
	"LRD":          69,
	"LTL":          70,
	"LVL":          71,
	"LYD":          72,
	"MAD":          73,
	"MKD":          74,
	"MNT":          75,
	"MUR":          76,
	"MXN":          77,
	"MWK":          78,
	"MYR":          79,
	"MZN":          80,
	"NAD":          81,
	"NGN":          82,
	"NIO":          83,
	"NOK":          84,
	"NPR":          85,
	"NZD":          86,
	"OMR":          87,
	"PAB":          88,
	"PEN":          89,
	"PHP":          90,
	"PKR":          91,
	"PLN":          92,
	"PYG":          93,
	"QAR":          94,
	"RON":          95,
	"RSD":          96,
	"RUB":          97,
	"RUR":          98,
	"SAR":          99,
	"SBD":          100,
	"SCR":          101,
	"SEK":          102,
	"SGD":          103,
	"SHP":          104,
	"SOS":          105,
	"SRD":          106,
	"SVC":          107,
	"SYP":          108,
	"THB":          109,
	"TND":          110,
	"TRL":          111,
	"TRY":          112,
	"TTD":          113,
	"TWD":          114,
	"TZS":          115,
	"UAH":          116,
	"UGX":          117,
	"AED":          118,
	"UYU":          119,
	"UZS":          120,
	"VEF":          121,
	"VND":          122,
	"XCD":          123,
	"YER":          124,
	"ZAR":          125,
	"ZMW":          126,
	"ZWD":          127,
	"USD":          128,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}
func (Currency) EnumDescriptor() ([]byte, []int) { return fileDescriptorPayment, []int{0} }

type ChargeStatus int32

const (
	ChargeStatus_Paid     ChargeStatus = 0
	ChargeStatus_Refunded ChargeStatus = 1
)

var ChargeStatus_name = map[int32]string{
	0: "Paid",
	1: "Refunded",
}
var ChargeStatus_value = map[string]int32{
	"Paid":     0,
	"Refunded": 1,
}

func (x ChargeStatus) String() string {
	return proto.EnumName(ChargeStatus_name, int32(x))
}
func (ChargeStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptorPayment, []int{1} }

type CardType int32

const (
	CardType_CARD_Reserved   CardType = 0
	CardType_Mastercard      CardType = 1
	CardType_Visa            CardType = 2
	CardType_AmericanExpress CardType = 3
	CardType_JCB             CardType = 4
	CardType_Discover        CardType = 5
	CardType_DinersClub      CardType = 6
)

var CardType_name = map[int32]string{
	0: "CARD_Reserved",
	1: "Mastercard",
	2: "Visa",
	3: "AmericanExpress",
	4: "JCB",
	5: "Discover",
	6: "DinersClub",
}
var CardType_value = map[string]int32{
	"CARD_Reserved":   0,
	"Mastercard":      1,
	"Visa":            2,
	"AmericanExpress": 3,
	"JCB":             4,
	"Discover":        5,
	"DinersClub":      6,
}

func (x CardType) String() string {
	return proto.EnumName(CardType_name, int32(x))
}
func (CardType) EnumDescriptor() ([]byte, []int) { return fileDescriptorPayment, []int{2} }

type PaymentProviderId int32

const (
	PaymentProviderId_PROVIDER_Reserved PaymentProviderId = 0
	PaymentProviderId_Stripe            PaymentProviderId = 1
	PaymentProviderId_Paypal            PaymentProviderId = 2
	PaymentProviderId_Braintree         PaymentProviderId = 3
)

var PaymentProviderId_name = map[int32]string{
	0: "PROVIDER_Reserved",
	1: "Stripe",
	2: "Paypal",
	3: "Braintree",
}
var PaymentProviderId_value = map[string]int32{
	"PROVIDER_Reserved": 0,
	"Stripe":            1,
	"Paypal":            2,
	"Braintree":         3,
}

func (x PaymentProviderId) String() string {
	return proto.EnumName(PaymentProviderId_name, int32(x))
}
func (PaymentProviderId) EnumDescriptor() ([]byte, []int) { return fileDescriptorPayment, []int{3} }

type RefundReason int32

const (
	RefundReason_GeneralError        RefundReason = 0
	RefundReason_Fraud               RefundReason = 1
	RefundReason_Duplicate           RefundReason = 2
	RefundReason_RequestedByCustomer RefundReason = 3
)

var RefundReason_name = map[int32]string{
	0: "GeneralError",
	1: "Fraud",
	2: "Duplicate",
	3: "RequestedByCustomer",
}
var RefundReason_value = map[string]int32{
	"GeneralError":        0,
	"Fraud":               1,
	"Duplicate":           2,
	"RequestedByCustomer": 3,
}

func (x RefundReason) String() string {
	return proto.EnumName(RefundReason_name, int32(x))
}
func (RefundReason) EnumDescriptor() ([]byte, []int) { return fileDescriptorPayment, []int{4} }

type ListRequest_Sort int32

const (
	ListRequest_Natural     ListRequest_Sort = 0
	ListRequest_CreatedDesc ListRequest_Sort = 1
	ListRequest_CreatedAsc  ListRequest_Sort = 2
	ListRequest_UpdatedDesc ListRequest_Sort = 3
	ListRequest_UpdatedAsc  ListRequest_Sort = 4
)

var ListRequest_Sort_name = map[int32]string{
	0: "Natural",
	1: "CreatedDesc",
	2: "CreatedAsc",
	3: "UpdatedDesc",
	4: "UpdatedAsc",
}
var ListRequest_Sort_value = map[string]int32{
	"Natural":     0,
	"CreatedDesc": 1,
	"CreatedAsc":  2,
	"UpdatedDesc": 3,
	"UpdatedAsc":  4,
}

func (x ListRequest_Sort) String() string {
	return proto.EnumName(ListRequest_Sort_name, int32(x))
}
func (ListRequest_Sort) EnumDescriptor() ([]byte, []int) { return fileDescriptorPayment, []int{6, 0} }

type Charge struct {
	Id               string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	Statement        string            `protobuf:"bytes,2,opt,name=statement,proto3" json:"statement,omitempty"`
	ChargeAmount     uint64            `protobuf:"varint,3,opt,name=chargeAmount,proto3" json:"chargeAmount,omitempty"`
	RefundAmount     uint64            `protobuf:"varint,4,opt,name=refundAmount,proto3" json:"refundAmount,omitempty"`
	Refunds          []*Refund         `protobuf:"bytes,5,rep,name=refunds" json:"refunds,omitempty"`
	Currency         Currency          `protobuf:"varint,6,opt,name=currency,proto3,enum=paymentpb.Currency" json:"currency,omitempty"`
	Email            string            `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Paid             bool              `protobuf:"varint,8,opt,name=paid,proto3" json:"paid,omitempty"`
	Refunded         bool              `protobuf:"varint,9,opt,name=refunded,proto3" json:"refunded,omitempty"`
	ProviderId       PaymentProviderId `protobuf:"varint,10,opt,name=providerId,proto3,enum=paymentpb.PaymentProviderId" json:"providerId,omitempty"`
	ProviderChargeId string            `protobuf:"bytes,11,opt,name=providerChargeId,proto3" json:"providerChargeId,omitempty"`
	Created          int64             `protobuf:"varint,998,opt,name=created,proto3" json:"created,omitempty"`
	Updated          int64             `protobuf:"varint,999,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (m *Charge) Reset()                    { *m = Charge{} }
func (m *Charge) String() string            { return proto.CompactTextString(m) }
func (*Charge) ProtoMessage()               {}
func (*Charge) Descriptor() ([]byte, []int) { return fileDescriptorPayment, []int{0} }

func (m *Charge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Charge) GetStatement() string {
	if m != nil {
		return m.Statement
	}
	return ""
}

func (m *Charge) GetChargeAmount() uint64 {
	if m != nil {
		return m.ChargeAmount
	}
	return 0
}

func (m *Charge) GetRefundAmount() uint64 {
	if m != nil {
		return m.RefundAmount
	}
	return 0
}

func (m *Charge) GetRefunds() []*Refund {
	if m != nil {
		return m.Refunds
	}
	return nil
}

func (m *Charge) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_CUR_RESERVED
}

func (m *Charge) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Charge) GetPaid() bool {
	if m != nil {
		return m.Paid
	}
	return false
}

func (m *Charge) GetRefunded() bool {
	if m != nil {
		return m.Refunded
	}
	return false
}

func (m *Charge) GetProviderId() PaymentProviderId {
	if m != nil {
		return m.ProviderId
	}
	return PaymentProviderId_PROVIDER_Reserved
}

func (m *Charge) GetProviderChargeId() string {
	if m != nil {
		return m.ProviderChargeId
	}
	return ""
}

func (m *Charge) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Charge) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type Refund struct {
	RefundAmount     uint64       `protobuf:"varint,1,opt,name=refundAmount,proto3" json:"refundAmount,omitempty"`
	ProviderRefundId string       `protobuf:"bytes,2,opt,name=providerRefundId,proto3" json:"providerRefundId,omitempty"`
	Reason           RefundReason `protobuf:"varint,3,opt,name=reason,proto3,enum=paymentpb.RefundReason" json:"reason,omitempty"`
	Created          int64        `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
}

func (m *Refund) Reset()                    { *m = Refund{} }
func (m *Refund) String() string            { return proto.CompactTextString(m) }
func (*Refund) ProtoMessage()               {}
func (*Refund) Descriptor() ([]byte, []int) { return fileDescriptorPayment, []int{1} }

func (m *Refund) GetRefundAmount() uint64 {
	if m != nil {
		return m.RefundAmount
	}
	return 0
}

func (m *Refund) GetProviderRefundId() string {
	if m != nil {
		return m.ProviderRefundId
	}
	return ""
}

func (m *Refund) GetReason() RefundReason {
	if m != nil {
		return m.Reason
	}
	return RefundReason_GeneralError
}

func (m *Refund) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type Card struct {
	Number      string   `protobuf:"bytes,1,opt,name=Number,proto3" json:"Number,omitempty" validate:"required,len=16"`
	ExpireMonth string   `protobuf:"bytes,2,opt,name=ExpireMonth,proto3" json:"ExpireMonth,omitempty" validate:"required,len=2"`
	ExpireYear  string   `protobuf:"bytes,3,opt,name=ExpireYear,proto3" json:"ExpireYear,omitempty" validate:"required,len=4"`
	FirstName   string   `protobuf:"bytes,4,opt,name=FirstName,proto3" json:"FirstName,omitempty" validate:"omitempty,min=1"`
	LastName    string   `protobuf:"bytes,5,opt,name=LastName,proto3" json:"LastName,omitempty" validate:"omitempty,min=1"`
	CVC         string   `protobuf:"bytes,6,opt,name=CVC,proto3" json:"CVC,omitempty" validate:"omitempty,len=3"`
	Type        CardType `protobuf:"varint,8,opt,name=type,proto3,enum=paymentpb.CardType" json:"type,omitempty" validate:"required,gte=1,lte=6"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptorPayment, []int{2} }

func (m *Card) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Card) GetExpireMonth() string {
	if m != nil {
		return m.ExpireMonth
	}
	return ""
}

func (m *Card) GetExpireYear() string {
	if m != nil {
		return m.ExpireYear
	}
	return ""
}

func (m *Card) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Card) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Card) GetCVC() string {
	if m != nil {
		return m.CVC
	}
	return ""
}

func (m *Card) GetType() CardType {
	if m != nil {
		return m.Type
	}
	return CardType_CARD_Reserved
}

type ChargeRequest struct {
	Currency          Currency          `protobuf:"varint,1,opt,name=currency,proto3,enum=paymentpb.Currency" json:"currency,omitempty" validate:"required,gte=1,lte=128"`
	Total             uint64            `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty" validate:"required,gte=0"`
	Card              *Card             `protobuf:"bytes,3,opt,name=Card" json:"Card,omitempty" validate:"required,dive"`
	Email             string            `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty" validate:"email"`
	Statement         string            `protobuf:"bytes,5,opt,name=statement,proto3" json:"statement,omitempty"`
	PaymentProviderId PaymentProviderId `protobuf:"varint,6,opt,name=paymentProviderId,proto3,enum=paymentpb.PaymentProviderId" json:"paymentProviderId,omitempty" validate:"required,gte=1,lte=3"`
	Metadata          map[string]string `protobuf:"bytes,7,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ChargeRequest) Reset()                    { *m = ChargeRequest{} }
func (m *ChargeRequest) String() string            { return proto.CompactTextString(m) }
func (*ChargeRequest) ProtoMessage()               {}
func (*ChargeRequest) Descriptor() ([]byte, []int) { return fileDescriptorPayment, []int{3} }

func (m *ChargeRequest) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_CUR_RESERVED
}

func (m *ChargeRequest) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ChargeRequest) GetCard() *Card {
	if m != nil {
		return m.Card
	}
	return nil
}

func (m *ChargeRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ChargeRequest) GetStatement() string {
	if m != nil {
		return m.Statement
	}
	return ""
}

func (m *ChargeRequest) GetPaymentProviderId() PaymentProviderId {
	if m != nil {
		return m.PaymentProviderId
	}
	return PaymentProviderId_PROVIDER_Reserved
}

func (m *ChargeRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type GetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"uuid4,required"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptorPayment, []int{4} }

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RefundRequest struct {
	Id     string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"uuid4,required"`
	Amount uint64       `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason RefundReason `protobuf:"varint,3,opt,name=reason,proto3,enum=paymentpb.RefundReason" json:"reason,omitempty" validate:"omitempty,gte=0,lte=3"`
}

func (m *RefundRequest) Reset()                    { *m = RefundRequest{} }
func (m *RefundRequest) String() string            { return proto.CompactTextString(m) }
func (*RefundRequest) ProtoMessage()               {}
func (*RefundRequest) Descriptor() ([]byte, []int) { return fileDescriptorPayment, []int{5} }

func (m *RefundRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RefundRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RefundRequest) GetReason() RefundReason {
	if m != nil {
		return m.Reason
	}
	return RefundReason_GeneralError
}

type ListRequest struct {
	Page  int64            `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty" validate:"omitempty,required,gte=0"`
	Limit int64            `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" validate:"omitempty,required,gt=0"`
	Sort  ListRequest_Sort `protobuf:"varint,3,opt,name=sort,proto3,enum=paymentpb.ListRequest_Sort" json:"sort,omitempty" validate:"omitempty,required,gte=0,lte=4"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptorPayment, []int{6} }

func (m *ListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetSort() ListRequest_Sort {
	if m != nil {
		return m.Sort
	}
	return ListRequest_Natural
}

type ChargeList struct {
	Charges []*Charge `protobuf:"bytes,1,rep,name=charges" json:"charges,omitempty"`
	Total   int32     `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *ChargeList) Reset()                    { *m = ChargeList{} }
func (m *ChargeList) String() string            { return proto.CompactTextString(m) }
func (*ChargeList) ProtoMessage()               {}
func (*ChargeList) Descriptor() ([]byte, []int) { return fileDescriptorPayment, []int{7} }

func (m *ChargeList) GetCharges() []*Charge {
	if m != nil {
		return m.Charges
	}
	return nil
}

func (m *ChargeList) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func init() {
	proto.RegisterType((*Charge)(nil), "paymentpb.charge")
	proto.RegisterType((*Refund)(nil), "paymentpb.refund")
	proto.RegisterType((*Card)(nil), "paymentpb.card")
	proto.RegisterType((*ChargeRequest)(nil), "paymentpb.chargeRequest")
	proto.RegisterType((*GetRequest)(nil), "paymentpb.getRequest")
	proto.RegisterType((*RefundRequest)(nil), "paymentpb.refundRequest")
	proto.RegisterType((*ListRequest)(nil), "paymentpb.listRequest")
	proto.RegisterType((*ChargeList)(nil), "paymentpb.chargeList")
	proto.RegisterEnum("paymentpb.Currency", Currency_name, Currency_value)
	proto.RegisterEnum("paymentpb.ChargeStatus", ChargeStatus_name, ChargeStatus_value)
	proto.RegisterEnum("paymentpb.CardType", CardType_name, CardType_value)
	proto.RegisterEnum("paymentpb.PaymentProviderId", PaymentProviderId_name, PaymentProviderId_value)
	proto.RegisterEnum("paymentpb.RefundReason", RefundReason_name, RefundReason_value)
	proto.RegisterEnum("paymentpb.ListRequest_Sort", ListRequest_Sort_name, ListRequest_Sort_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Payment service

type PaymentClient interface {
	Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*Charge, error)
	Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*Charge, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Charge, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ChargeList, error)
}

type paymentClient struct {
	cc *grpc.ClientConn
}

func NewPaymentClient(cc *grpc.ClientConn) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) Charge(ctx context.Context, in *ChargeRequest, opts ...grpc.CallOption) (*Charge, error) {
	out := new(Charge)
	err := grpc.Invoke(ctx, "/paymentpb.Payment/Charge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) Refund(ctx context.Context, in *RefundRequest, opts ...grpc.CallOption) (*Charge, error) {
	out := new(Charge)
	err := grpc.Invoke(ctx, "/paymentpb.Payment/Refund", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Charge, error) {
	out := new(Charge)
	err := grpc.Invoke(ctx, "/paymentpb.Payment/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ChargeList, error) {
	out := new(ChargeList)
	err := grpc.Invoke(ctx, "/paymentpb.Payment/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Payment service

type PaymentServer interface {
	Charge(context.Context, *ChargeRequest) (*Charge, error)
	Refund(context.Context, *RefundRequest) (*Charge, error)
	Get(context.Context, *GetRequest) (*Charge, error)
	List(context.Context, *ListRequest) (*ChargeList, error)
}

func RegisterPaymentServer(s *grpc.Server, srv PaymentServer) {
	s.RegisterService(&_Payment_serviceDesc, srv)
}

func _Payment_Charge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).Charge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.Payment/Charge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).Charge(ctx, req.(*ChargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.Payment/Refund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).Refund(ctx, req.(*RefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.Payment/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paymentpb.Payment/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Payment_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paymentpb.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Charge",
			Handler:    _Payment_Charge_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _Payment_Refund_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Payment_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Payment_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/paymentpb/payment.proto",
}

func init() { proto.RegisterFile("payment/paymentpb/payment.proto", fileDescriptorPayment) }

var fileDescriptorPayment = []byte{
	// 1896 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd8, 0xdb, 0x5e, 0xdb, 0xc8,
	0x19, 0x00, 0x70, 0x7c, 0xc4, 0x1e, 0x02, 0xf9, 0x32, 0x39, 0x39, 0x6c, 0x36, 0x66, 0x95, 0xdd,
	0x2c, 0xcb, 0x12, 0x08, 0x24, 0xcd, 0xa6, 0x24, 0x74, 0x6b, 0x79, 0x8c, 0x21, 0xb6, 0x65, 0x31,
	0xc6, 0x38, 0x76, 0xdb, 0x4d, 0x85, 0x35, 0x21, 0xea, 0xda, 0x96, 0xa3, 0x03, 0x0d, 0x3d, 0xbf,
	0x47, 0x7f, 0xbd, 0xea, 0x75, 0xef, 0x7b, 0xd7, 0x77, 0xe8, 0x03, 0xf8, 0xb2, 0x7b, 0xef, 0x27,
	0xe8, 0x6f, 0x3e, 0xc9, 0x60, 0x30, 0x64, 0xf3, 0xdb, 0x2b, 0xfe, 0xa3, 0xf9, 0xbe, 0xd1, 0x8c,
	0x66, 0x34, 0x63, 0x41, 0xb2, 0x7d, 0xe3, 0xb8, 0x2b, 0x7a, 0xde, 0x6a, 0xf8, 0xb7, 0x7f, 0x30,
	0xd2, 0x4a, 0xdf, 0xb1, 0x3d, 0x9b, 0xa6, 0x4f, 0x2a, 0xe6, 0x1f, 0x1e, 0x5a, 0xde, 0x5b, 0xff,
	0x60, 0xa5, 0x6d, 0x77, 0x57, 0x0f, 0xed, 0x43, 0x7b, 0x15, 0x23, 0x0e, 0xfc, 0x37, 0x58, 0xc2,
	0x02, 0x2a, 0xc8, 0x54, 0xfe, 0x1b, 0x23, 0xc9, 0xf6, 0x5b, 0xc3, 0x39, 0x14, 0xf4, 0x1e, 0x89,
	0x5a, 0x66, 0x26, 0xb2, 0x10, 0x59, 0x4c, 0xab, 0x73, 0xc3, 0x41, 0x96, 0x1c, 0xb8, 0x76, 0x6f,
	0x43, 0x79, 0x6d, 0x99, 0x0a, 0x8f, 0x5a, 0x26, 0xbd, 0x4b, 0xd2, 0xae, 0x67, 0x78, 0x42, 0xde,
	0x28, 0x13, 0x95, 0x61, 0xfc, 0xf4, 0x02, 0x55, 0xc8, 0x95, 0xa0, 0x9d, 0x5c, 0xd7, 0xf6, 0x7b,
	0x5e, 0x26, 0xb6, 0x10, 0x59, 0x8c, 0xf3, 0x33, 0xd7, 0x64, 0x8c, 0x23, 0xde, 0xf8, 0x3d, 0x33,
	0x8c, 0x89, 0x07, 0x31, 0xe3, 0xd7, 0xe8, 0xd7, 0x64, 0x3a, 0x28, 0xbb, 0x99, 0xc4, 0x42, 0x6c,
	0x71, 0x66, 0xfd, 0xda, 0xca, 0xc9, 0xe0, 0x56, 0x82, 0x1a, 0x3e, 0x8a, 0xa0, 0xab, 0x24, 0xd5,
	0xf6, 0x1d, 0x47, 0xf4, 0xda, 0xc7, 0x99, 0xe4, 0x42, 0x64, 0x71, 0x6e, 0xfd, 0xfa, 0x58, 0xf4,
	0xa8, 0x8a, 0x9f, 0x04, 0xd1, 0x1b, 0x24, 0x21, 0xba, 0x86, 0xd5, 0xc9, 0x4c, 0x63, 0xff, 0x83,
	0x02, 0xa5, 0x24, 0xde, 0x37, 0x2c, 0x33, 0x93, 0x5a, 0x88, 0x2c, 0xa6, 0x38, 0x9a, 0xce, 0x93,
	0x54, 0x70, 0x17, 0x61, 0x66, 0xd2, 0x78, 0xfd, 0xa4, 0x4c, 0x5f, 0x10, 0xd2, 0x77, 0xec, 0x23,
	0xcb, 0x14, 0xce, 0x8e, 0x99, 0x21, 0x78, 0xe3, 0xbb, 0x63, 0x37, 0x0e, 0xa5, 0x9f, 0xc4, 0xf0,
	0xb1, 0x78, 0xba, 0x44, 0x60, 0x54, 0xca, 0xe3, 0xd3, 0xd9, 0x31, 0x33, 0x33, 0xd8, 0x9d, 0x89,
	0xeb, 0xf4, 0x0e, 0x99, 0x6e, 0x3b, 0xc2, 0xf0, 0x84, 0x99, 0xf9, 0x9f, 0xec, 0x72, 0x8c, 0x8f,
	0xca, 0xb2, 0xca, 0xef, 0x9b, 0x58, 0xf5, 0x43, 0x58, 0x15, 0x96, 0x95, 0x7f, 0x46, 0x48, 0x32,
	0xe8, 0xec, 0xc4, 0x23, 0x8f, 0x5c, 0xf0, 0xc8, 0xc7, 0x3a, 0xc4, 0xf1, 0xfa, 0x8e, 0x19, 0xce,
	0xef, 0xc4, 0x75, 0xba, 0x2a, 0x5b, 0x36, 0x5c, 0xbb, 0x87, 0x13, 0x3c, 0xb7, 0x7e, 0x7b, 0x72,
	0x76, 0xb0, 0x9a, 0x87, 0x61, 0x34, 0x73, 0x3a, 0x82, 0xf8, 0x99, 0x01, 0x28, 0xff, 0x8e, 0x91,
	0x78, 0xdb, 0x70, 0x4c, 0xfa, 0x94, 0x24, 0x35, 0xbf, 0x7b, 0x20, 0x9c, 0x70, 0xf1, 0xdd, 0x1b,
	0x0e, 0xb2, 0xf3, 0x47, 0x46, 0xc7, 0x92, 0xa3, 0xd9, 0x50, 0x1c, 0xf1, 0xce, 0xb7, 0x1c, 0x61,
	0x2e, 0x77, 0x44, 0x6f, 0x73, 0xed, 0xa9, 0xc2, 0xc3, 0x68, 0xfa, 0x2d, 0x99, 0x29, 0xbc, 0xef,
	0x5b, 0x8e, 0xa8, 0xd8, 0x3d, 0xef, 0x6d, 0xd0, 0x65, 0xf5, 0xd3, 0xe1, 0x20, 0x7b, 0xe7, 0x92,
	0xe4, 0x75, 0x85, 0x8f, 0x67, 0xd0, 0x4d, 0x42, 0x82, 0x62, 0x53, 0x18, 0x0e, 0x0e, 0xe8, 0xc3,
	0xf9, 0x4f, 0x14, 0x3e, 0x96, 0x40, 0x5f, 0x90, 0xf4, 0x96, 0xe5, 0xb8, 0x9e, 0x66, 0x74, 0x05,
	0x0e, 0x6e, 0xa2, 0xeb, 0x76, 0xd7, 0xf2, 0x44, 0xb7, 0xef, 0x1d, 0x2f, 0x77, 0xad, 0xde, 0xe6,
	0x9a, 0xc2, 0x4f, 0x13, 0xe8, 0x06, 0x49, 0x95, 0x8d, 0x30, 0x39, 0xf1, 0x51, 0xc9, 0x27, 0xf1,
	0xf4, 0x11, 0x89, 0xe5, 0xf7, 0xf3, 0xb8, 0xe4, 0x3f, 0x90, 0x26, 0xbb, 0xfc, 0x58, 0xe1, 0x32,
	0x94, 0x96, 0x49, 0xdc, 0x3b, 0xee, 0x0b, 0x5c, 0xe2, 0xe7, 0xde, 0x12, 0xc3, 0x31, 0xf7, 0x8e,
	0xfb, 0x42, 0xbd, 0x3f, 0x1c, 0x64, 0xb3, 0x17, 0x8c, 0xfc, 0xd0, 0x13, 0x9b, 0x6b, 0xcb, 0x1d,
	0x4f, 0x6c, 0x3e, 0x55, 0x38, 0xb6, 0xa2, 0xfc, 0x3d, 0x4e, 0x66, 0x83, 0x37, 0x9b, 0x8b, 0x77,
	0xbe, 0x70, 0x3d, 0xba, 0x3f, 0xf6, 0x26, 0x46, 0x2e, 0x7d, 0x13, 0xd5, 0x2f, 0x86, 0x83, 0xec,
	0x67, 0x1f, 0xbc, 0xc7, 0xda, 0xfa, 0x33, 0x65, 0xec, 0x85, 0x7d, 0x4c, 0x12, 0x9e, 0xed, 0x19,
	0x1d, 0x9c, 0xdd, 0xf8, 0xa5, 0xb3, 0x23, 0xf3, 0x1f, 0x29, 0x3c, 0x88, 0xa5, 0x39, 0x12, 0xcf,
	0x1b, 0x8e, 0x89, 0x33, 0x3a, 0xb3, 0x7e, 0xf5, 0xdc, 0x60, 0xd5, 0xbb, 0xc3, 0x41, 0x36, 0x73,
	0x41, 0x23, 0xa6, 0x75, 0x24, 0x14, 0x8e, 0xa9, 0x74, 0x69, 0xb4, 0x51, 0x04, 0xf3, 0x7a, 0x63,
	0x38, 0xc8, 0xc2, 0x69, 0x0a, 0x56, 0x29, 0xa3, 0xed, 0xe3, 0xcc, 0xc6, 0x98, 0x38, 0xbf, 0x31,
	0xda, 0xe4, 0xda, 0xc4, 0x7e, 0x10, 0x6e, 0x56, 0x1f, 0xdc, 0x33, 0x3e, 0x62, 0x3e, 0x1e, 0x2b,
	0x7c, 0xb2, 0x6d, 0xaa, 0x92, 0x54, 0x57, 0x78, 0x86, 0x69, 0x78, 0x46, 0x66, 0x1a, 0xb7, 0xd0,
	0x07, 0xe3, 0x4f, 0x60, 0x7c, 0xda, 0x56, 0x2a, 0x61, 0x60, 0xa1, 0xe7, 0x39, 0xc7, 0xfc, 0x24,
	0x6f, 0xfe, 0x39, 0x99, 0x3d, 0x53, 0x45, 0x81, 0xc4, 0xbe, 0x17, 0xc1, 0xd4, 0xa6, 0xb9, 0xa4,
	0xdc, 0x4a, 0x8f, 0x8c, 0x8e, 0x2f, 0xc2, 0xad, 0x22, 0x28, 0x6c, 0x44, 0x9f, 0x45, 0x94, 0xe7,
	0x84, 0x1c, 0x0a, 0x6f, 0xb4, 0x32, 0x1e, 0x8e, 0x1d, 0x2b, 0xe7, 0xa6, 0xcf, 0xf7, 0x2d, 0xf3,
	0xc9, 0xf2, 0x68, 0x60, 0x78, 0xca, 0x28, 0xff, 0x8a, 0x90, 0xd9, 0xd1, 0x46, 0xf2, 0x53, 0x1a,
	0xa0, 0xb7, 0x48, 0xd2, 0x08, 0xf6, 0x3a, 0x5c, 0x32, 0x3c, 0x2c, 0xd1, 0xfa, 0x47, 0xee, 0x5c,
	0xea, 0xe7, 0xc3, 0x41, 0x76, 0xe1, 0xa2, 0xf7, 0x09, 0x17, 0xd9, 0xe8, 0xc1, 0x87, 0x8d, 0x29,
	0xff, 0x89, 0x92, 0x99, 0x8e, 0xe5, 0x9e, 0x0c, 0xf7, 0xb9, 0x3c, 0x4b, 0x0e, 0x05, 0xf6, 0x37,
	0xa6, 0x7e, 0x39, 0x1c, 0x64, 0xef, 0x5f, 0xd4, 0xd6, 0xf9, 0x95, 0x8b, 0x49, 0xf4, 0x05, 0x49,
	0x74, 0xac, 0xae, 0x15, 0x74, 0x3d, 0xa6, 0x3e, 0x18, 0x0e, 0xb2, 0xca, 0x8f, 0x64, 0xe3, 0xb2,
	0xc7, 0x24, 0xfa, 0x1d, 0x89, 0xbb, 0xb6, 0xe3, 0x85, 0xe3, 0xfb, 0x64, 0x6c, 0x7c, 0x63, 0x1d,
	0x5c, 0xa9, 0xd9, 0x8e, 0xa7, 0x3e, 0x1c, 0x0e, 0xb2, 0x5f, 0xfd, 0x78, 0xbf, 0x70, 0xb0, 0x4f,
	0x14, 0x8e, 0xed, 0x2a, 0x75, 0x12, 0x97, 0xc9, 0x74, 0x86, 0x4c, 0x6b, 0x86, 0xe7, 0x3b, 0x46,
	0x07, 0xa6, 0xe8, 0x55, 0x32, 0x93, 0x0f, 0x36, 0x74, 0x26, 0xdc, 0x36, 0x44, 0xe8, 0x1c, 0x21,
	0xe1, 0x85, 0x9c, 0xdb, 0x86, 0xa8, 0x0c, 0xa8, 0x07, 0xe7, 0x12, 0x06, 0xc4, 0x64, 0x40, 0x78,
	0x41, 0x06, 0xc4, 0x95, 0x2a, 0x21, 0xc1, 0xa2, 0x2c, 0x5b, 0x2e, 0x9e, 0xff, 0x41, 0xc9, 0xcd,
	0x44, 0x26, 0xce, 0xff, 0x70, 0xf1, 0x8e, 0x22, 0xe4, 0x1a, 0x3c, 0xdd, 0x1d, 0x12, 0xe1, 0xeb,
	0xbf, 0xf4, 0x8f, 0xf4, 0xe9, 0x66, 0x44, 0x81, 0x5c, 0xc9, 0xd7, 0xf9, 0x6b, 0x5e, 0xa8, 0x15,
	0xf8, 0x7e, 0x81, 0xc1, 0x14, 0x9d, 0x26, 0xb1, 0xdc, 0x96, 0x06, 0x11, 0x44, 0xb9, 0x0c, 0x51,
	0x44, 0x85, 0x41, 0x0c, 0xa1, 0x15, 0x21, 0x8e, 0xe0, 0x35, 0x48, 0x20, 0xea, 0x0c, 0x92, 0x88,
	0x46, 0x11, 0xa6, 0x11, 0x2d, 0x0d, 0x52, 0x12, 0x6a, 0xae, 0x02, 0x69, 0x84, 0xca, 0x80, 0x20,
	0x8a, 0x1a, 0xcc, 0x20, 0xb6, 0x19, 0x5c, 0x41, 0x54, 0x18, 0xcc, 0x22, 0x34, 0x06, 0x73, 0x88,
	0xaa, 0x0a, 0x57, 0x11, 0xbc, 0x0c, 0x80, 0xa8, 0x31, 0xb8, 0x86, 0x68, 0xe8, 0x40, 0x11, 0x4d,
	0x0d, 0xae, 0x07, 0xe0, 0x70, 0x03, 0xd1, 0x62, 0x70, 0x53, 0x22, 0x9f, 0x63, 0x70, 0x0b, 0x51,
	0xd6, 0xe1, 0x36, 0x42, 0x6b, 0x42, 0x06, 0x51, 0xd5, 0xe1, 0x0e, 0x82, 0xe7, 0x61, 0x1e, 0x51,
	0xd7, 0xe1, 0x13, 0x44, 0xab, 0x04, 0x77, 0x25, 0x58, 0xa9, 0x04, 0x9f, 0x22, 0xaa, 0x3a, 0xdc,
	0x43, 0xb4, 0x18, 0x64, 0x25, 0x0a, 0x85, 0x12, 0x2c, 0x20, 0x8a, 0x3a, 0x7c, 0x86, 0xa8, 0x73,
	0x50, 0x24, 0xb6, 0x5e, 0x32, 0xb8, 0x8f, 0x28, 0xe9, 0xf0, 0xb9, 0x44, 0x51, 0xd5, 0xe1, 0x0b,
	0x44, 0x51, 0x87, 0x07, 0x88, 0xed, 0x3c, 0x7c, 0x89, 0xd8, 0xd1, 0x61, 0x11, 0xb1, 0xb7, 0x0b,
	0x5f, 0x21, 0x9a, 0x0c, 0x96, 0x24, 0xb6, 0x4b, 0x0c, 0xbe, 0x46, 0x68, 0x65, 0x58, 0x46, 0xf0,
	0x12, 0x3c, 0x44, 0xd4, 0xb7, 0x60, 0x45, 0x62, 0x87, 0x71, 0x58, 0x45, 0x94, 0x6b, 0xf0, 0x08,
	0x51, 0xd1, 0x61, 0x0d, 0xa1, 0x71, 0x58, 0x47, 0xec, 0x32, 0x78, 0x8c, 0xe0, 0x1c, 0x9e, 0x20,
	0x6a, 0x25, 0xf8, 0x99, 0xc4, 0xcb, 0x82, 0x0e, 0x4f, 0x11, 0x15, 0x06, 0xdf, 0x20, 0xaa, 0x0c,
	0x9e, 0x21, 0xf4, 0x26, 0xfc, 0x5c, 0xa2, 0x54, 0xa8, 0xc1, 0x06, 0xa2, 0x58, 0x83, 0xe7, 0x88,
	0x6d, 0x0e, 0x2f, 0x10, 0x7a, 0x03, 0x36, 0x11, 0xbc, 0x01, 0xbf, 0x40, 0x34, 0x18, 0x7c, 0x8b,
	0x68, 0x32, 0xf8, 0x25, 0xa2, 0xb5, 0x07, 0x39, 0x89, 0x72, 0xae, 0x04, 0x2a, 0x42, 0xd5, 0x21,
	0x8f, 0x28, 0x71, 0x60, 0x08, 0xce, 0xa0, 0x80, 0xd8, 0x2b, 0xc3, 0x16, 0x62, 0xbf, 0x0c, 0x45,
	0x44, 0x93, 0xc1, 0xb6, 0x44, 0x25, 0xc7, 0x60, 0x07, 0x51, 0x62, 0xf0, 0x12, 0xa1, 0xed, 0x41,
	0x09, 0x51, 0xe7, 0x50, 0x46, 0xbc, 0xd2, 0xa0, 0x82, 0x68, 0x94, 0x40, 0x43, 0x34, 0x39, 0x54,
	0x11, 0x2d, 0x0d, 0x74, 0x09, 0x2d, 0xc7, 0x60, 0x17, 0x51, 0xd4, 0x80, 0x23, 0x76, 0xaa, 0x50,
	0x43, 0x54, 0x4b, 0xb0, 0x87, 0xd0, 0x39, 0xd4, 0x11, 0x2d, 0x06, 0xfb, 0x12, 0xd5, 0x0a, 0x87,
	0x86, 0x84, 0x9e, 0x53, 0xe1, 0x15, 0xa2, 0xa0, 0x41, 0x13, 0xb1, 0xad, 0x43, 0x0b, 0x51, 0xe2,
	0xf0, 0x2b, 0x44, 0x59, 0x83, 0x5f, 0x23, 0x9a, 0x45, 0xf8, 0x8d, 0xc4, 0x6e, 0x8e, 0xc3, 0x77,
	0x12, 0xbc, 0xaa, 0xc1, 0x6b, 0x44, 0x8d, 0xc1, 0x6f, 0x11, 0x75, 0x15, 0x8c, 0x00, 0x1c, 0x0e,
	0x24, 0x6a, 0x39, 0x0e, 0x6d, 0x84, 0xca, 0xc0, 0x44, 0xe4, 0x39, 0x08, 0x44, 0xa1, 0x04, 0x6f,
	0x10, 0x45, 0x06, 0x87, 0x88, 0x6d, 0x1d, 0xde, 0x22, 0xaa, 0x35, 0xb0, 0x10, 0x9c, 0xc1, 0xef,
	0x10, 0xfb, 0x79, 0xf8, 0x1e, 0xd1, 0xd4, 0xa1, 0x23, 0xb1, 0xb7, 0xad, 0x42, 0x17, 0xa1, 0x31,
	0xe8, 0x21, 0x78, 0x19, 0xec, 0x00, 0x4d, 0xe8, 0x23, 0xf6, 0x18, 0xbc, 0x43, 0x34, 0x18, 0x38,
	0x88, 0x56, 0x0d, 0x5c, 0x89, 0x7a, 0x6e, 0x1b, 0x3c, 0x44, 0xf1, 0x15, 0xf8, 0xf8, 0x76, 0x17,
	0x18, 0x1c, 0xe1, 0x95, 0x66, 0x1d, 0x7e, 0x8f, 0x68, 0xd5, 0xe0, 0xbd, 0xc4, 0x7e, 0x61, 0x0b,
	0x8e, 0x11, 0x1a, 0x83, 0x3f, 0x48, 0xbc, 0xca, 0x33, 0xf8, 0xa3, 0x44, 0xb3, 0xc0, 0xe1, 0x4f,
	0x12, 0xad, 0x1c, 0x87, 0x3f, 0x23, 0x2a, 0x0d, 0xf8, 0x0b, 0xa2, 0xc1, 0xe0, 0xaf, 0x34, 0x45,
	0x62, 0xf5, 0x1a, 0x83, 0xbf, 0x45, 0x96, 0x1e, 0x8c, 0x3e, 0x95, 0x6a, 0x9e, 0xe1, 0xf9, 0x2e,
	0x4d, 0x91, 0xb8, 0x6e, 0x58, 0x26, 0x4c, 0xd1, 0x2b, 0x24, 0xc5, 0xc3, 0x8f, 0x0c, 0x88, 0x2c,
	0xb9, 0x24, 0x35, 0xfa, 0x71, 0x46, 0xaf, 0x91, 0xd9, 0x7c, 0x8e, 0xb3, 0xd7, 0x5c, 0xb8, 0xc2,
	0x39, 0x12, 0x32, 0x78, 0x8e, 0x90, 0x8a, 0xe1, 0x7a, 0xc2, 0x91, 0x41, 0x10, 0x91, 0xcd, 0xec,
	0x5b, 0xae, 0x01, 0x51, 0x7a, 0x9d, 0x5c, 0xcd, 0x75, 0x85, 0x63, 0xb5, 0x8d, 0x5e, 0xe1, 0x7d,
	0xdf, 0x11, 0xae, 0x1b, 0xec, 0x6d, 0x2f, 0xf3, 0x2a, 0xc4, 0xe5, 0x4d, 0x98, 0xe5, 0xb6, 0xed,
	0x23, 0xe1, 0x40, 0x42, 0xb6, 0xc2, 0xac, 0x9e, 0x70, 0xdc, 0x7c, 0xc7, 0x3f, 0x80, 0xe4, 0xd2,
	0xee, 0x05, 0x3f, 0x57, 0xe8, 0x4d, 0x72, 0x4d, 0xe7, 0xd5, 0xfd, 0x1d, 0x56, 0xe0, 0xe3, 0x3d,
	0x20, 0x24, 0x59, 0xf3, 0x1c, 0xab, 0x2f, 0x20, 0x22, 0xad, 0x1b, 0xc7, 0x7d, 0xa3, 0x03, 0x51,
	0x3a, 0x4b, 0xd2, 0xaa, 0x63, 0x58, 0x3d, 0xcf, 0x11, 0x02, 0x62, 0x4b, 0xb5, 0xd1, 0x37, 0x48,
	0x70, 0xc0, 0xca, 0x2d, 0xb9, 0x28, 0x7a, 0xc2, 0x31, 0x3a, 0x05, 0xc7, 0xb1, 0x1d, 0x98, 0xa2,
	0x69, 0x92, 0xd8, 0x72, 0x0c, 0x5f, 0x8e, 0x62, 0x96, 0xa4, 0x99, 0xdf, 0xef, 0x58, 0x6d, 0xc3,
	0x13, 0x10, 0xa5, 0xb7, 0xc9, 0xf5, 0xf0, 0xe0, 0x12, 0xa6, 0x7a, 0x9c, 0xf7, 0x5d, 0xcf, 0xee,
	0x0a, 0x07, 0x62, 0xeb, 0x3f, 0x44, 0xc8, 0xb4, 0x1e, 0x74, 0x94, 0x7e, 0x43, 0x92, 0xc1, 0x17,
	0x13, 0xcd, 0x5c, 0xf6, 0x4b, 0x67, 0x7e, 0xf2, 0x18, 0x51, 0xa6, 0x64, 0x62, 0xf0, 0xbc, 0xcf,
	0x24, 0x9e, 0xf9, 0xf9, 0x71, 0x71, 0xe2, 0x1a, 0x89, 0x15, 0x85, 0x47, 0x6f, 0x8e, 0xd5, 0x9d,
	0xfe, 0xe4, 0xb9, 0xec, 0x5e, 0x71, 0x3c, 0xe0, 0x6e, 0x5d, 0x7c, 0x2e, 0xcf, 0xdf, 0x9c, 0x48,
	0x92, 0xe1, 0xca, 0x94, 0xba, 0xdc, 0x5a, 0x1a, 0xfb, 0xa6, 0x37, 0xad, 0x43, 0xdb, 0x33, 0x46,
	0x7f, 0x26, 0xfe, 0x31, 0x70, 0x90, 0xc4, 0xef, 0xfa, 0xc7, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0x4f, 0xce, 0x40, 0x64, 0x34, 0x10, 0x00, 0x00,
}
